default: &default
  adapter: postgresql
  pool: 5
  timeout: 10000
  encoding: unicode

development:
  <<: *default
  database: gretschlist_development

test:
  <<: *default
  database: gretschlist_test

production:
  <<: *default
  database: gretschlist_production
